# Generated by Django 5.2.5 on 2025-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cte', models.CharField(max_length=50)),
                ('serie_cte', models.CharField(max_length=10)),
                ('numero_protocolo', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('expedidor', models.TextField(blank=True)),
                ('remetente', models.TextField()),
                ('destinatario', models.TextField()),
                ('cidade_origem', models.CharField(max_length=100)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('volumes', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_nota_fiscal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('chave_cte', models.CharField(max_length=50, unique=True)),
                ('nota_fiscal', models.CharField(max_length=50)),
                ('numero_referencia', models.CharField(blank=True, max_length=50)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arquivo_xml', models.TextField(blank=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
