# Generated by Django 5.2.5 on 2025-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cte',
            options={'verbose_name': 'CTe', 'verbose_name_plural': 'CTes'},
        ),
        migrations.RemoveField(
            model_name='cte',
            name='expedidor',
        ),
        migrations.RemoveField(
            model_name='cte',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='cte',
            name='numero_protocolo',
        ),
        migrations.RemoveField(
            model_name='cte',
            name='numero_referencia',
        ),
        migrations.RemoveField(
            model_name='cte',
            name='valor_nota_fiscal',
        ),
        migrations.AddField(
            model_name='cte',
            name='advalorem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cte',
            name='cnpj_destinatario',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cte',
            name='cnpj_emitente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cte',
            name='cnpj_remetente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cte',
            name='frete_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cte',
            name='gerenciamento_risco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cte',
            name='icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cte',
            name='nome_fantasia_emitente',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cte',
            name='outros_valores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cte',
            name='pedagio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cte',
            name='razao_social_emitente',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cte',
            name='tomador_cnpj',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cte',
            name='tomador_razao_social',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cte',
            name='tomador_tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cte',
            name='uf_destino',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='cte',
            name='uf_origem',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='cte',
            name='chave_cte',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='cidade_destino',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cte',
            name='cidade_origem',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cte',
            name='data_emissao',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='destinatario',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='cte',
            name='numero_cte',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cte',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cte',
            name='remetente',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='cte',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cte',
            name='volumes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['data_emissao'], name='dashboard_c_data_em_956b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['cidade_origem', 'cidade_destino'], name='dashboard_c_cidade__00b1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['nome_fantasia_emitente'], name='dashboard_c_nome_fa_7be807_idx'),
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['tomador_cnpj'], name='dashboard_c_tomador_006ad4_idx'),
        ),
    ]
